- block:

  - name: make library directory
    file:
      path: ~/Library/Application Support/Cursor/User
      state: directory

  - name: basic settings
    file:
      src: ~/dotfiles/cursor/settings.json
      dest: ~/Library/Application Support/Cursor/User/settings.json
      state: link
      force: yes

  - name: keybindings
    file:
      src: ~/dotfiles/cursor/keybindings.json
      dest: ~/Library/Application Support/Cursor/User/keybindings.json
      state: link
      force: yes

  tags:
    - cursor
