- block:

  - name: create symbolic links
    file:
      src: ~/dotfiles/{{ item }}
      dest: ~/{{ item }}
      state: link
      force: yes
    with_items: '{{ dotfiles }}'

  tags:
    - dotfiles
