- block:

  - name: make .config directory
    file:
      path: ~/.config/karabiner
      state: directory

  - name: create symbolic links
    file:
      src: ~/dotfiles/karabiner/karabiner.json
      dest: ~/.config/karabiner/karabiner.json
      state: link
      force: yes
  
  tags:
    - karabiner
